version: '3.8'

networks: 
    lumen :
        driver: bridge

services:      
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: assetnest
            MYSQL_USER: iqbal
            MYSQL_PASSWORD: iqbal
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAG: dev
            SERVICE_NAME: mariadb
        networks: 
            - lumen

    assetnest:
        build: 
            context: .
            dockerfile: assetnest.Dockerfile
        container_name: assetnest
        volumes: 
            - ./letsencrypt:/etc/letsencrypt
        ports: 
            - "80:80"
            - "443:443"
        networks: 
            - lumen
        depends_on:
            - mariadb
    
    
